version: "3.9"

services:
  backend:
    build: ./backend
    container_name: privacy-risk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
  #   build: ./frontend
  #   container_name: privacy-risk-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

  db:
    image: postgres:16
    container_name: privacy-risk-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
