-- SQL Migration for PostgreSQL Tables

-- Create enum type for dataset_kind
CREATE TYPE dataset_kind AS ENUM ('real', 'synthetic');

-- Create dataset_uploads table
CREATE TABLE dataset_uploads (
    file_uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dataset_kind dataset_kind NOT NULL,
    input_filename VARCHAR NOT NULL,
    stored_filename VARCHAR NOT NULL,
    file_path VARCHAR NOT NULL,
    file_extension VARCHAR NOT NULL,
    file_size_bytes INTEGER NOT NULL,
    mime_type VARCHAR,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    row_count INTEGER,
    column_count INTEGER,
    status VARCHAR,
    notes TEXT
);

-- Create real_dataset_records table
CREATE TABLE real_dataset_records (
    record_uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    file_uuid UUID NOT NULL REFERENCES dataset_uploads(file_uuid),
    encounter_id VARCHAR,
    patient_nbr VARCHAR,
    race VARCHAR,
    gender VARCHAR,
    age VARCHAR,
    weight VARCHAR,
    admission_type_id VARCHAR,
    discharge_disposition_id VARCHAR,
    admission_source_id VARCHAR,
    time_in_hospital VARCHAR,
    payer_code VARCHAR,
    medical_specialty VARCHAR,
    num_lab_procedures VARCHAR,
    num_procedures VARCHAR,
    num_medications VARCHAR,
    number_outpatient VARCHAR,
    number_emergency VARCHAR,
    number_inpatient VARCHAR,
    diag_1 VARCHAR,
    diag_2 VARCHAR,
    diag_3 VARCHAR,
    number_diagnoses VARCHAR,
    max_glu_serum VARCHAR,
    A1Cresult VARCHAR,
    metformin VARCHAR,
    repaglinide VARCHAR,
    nateglinide VARCHAR,
    chlorpropamide VARCHAR,
    glimepiride VARCHAR,
    acetohexamide VARCHAR,
    glipizide VARCHAR,
    glyburide VARCHAR,
    tolbutamide VARCHAR,
    pioglitazone VARCHAR,
    rosiglitazone VARCHAR,
    acarbose VARCHAR,
    miglitol VARCHAR,
    troglitazone VARCHAR,
    tolazamide VARCHAR,
    examide VARCHAR,
    citoglipton VARCHAR,
    insulin VARCHAR,
    "glyburide-metformin" VARCHAR,
    "glipizide-metformin" VARCHAR,
    "glimepiride-pioglitazone" VARCHAR,
    "metformin-rosiglitazone" VARCHAR,
    "metformin-pioglitazone" VARCHAR,
    change VARCHAR,
    diabetesMed VARCHAR,
    readmitted VARCHAR
);

-- Create synthetic_dataset_records table
CREATE TABLE synthetic_dataset_records (
    record_uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    file_uuid UUID NOT NULL REFERENCES dataset_uploads(file_uuid),
    encounter_id VARCHAR,
    patient_nbr VARCHAR,
    race VARCHAR,
    gender VARCHAR,
    age VARCHAR,
    weight VARCHAR,
    admission_type_id VARCHAR,
    discharge_disposition_id VARCHAR,
    admission_source_id VARCHAR,
    time_in_hospital VARCHAR,
    payer_code VARCHAR,
    medical_specialty VARCHAR,
    num_lab_procedures VARCHAR,
    num_procedures VARCHAR,
    num_medications VARCHAR,
    number_outpatient VARCHAR,
    number_emergency VARCHAR,
    number_inpatient VARCHAR,
    diag_1 VARCHAR,
    diag_2 VARCHAR,
    diag_3 VARCHAR,
    number_diagnoses VARCHAR,
    max_glu_serum VARCHAR,
    A1Cresult VARCHAR,
    metformin VARCHAR,
    repaglinide VARCHAR,
    nateglinide VARCHAR,
    chlorpropamide VARCHAR,
    glimepiride VARCHAR,
    acetohexamide VARCHAR,
    glipizide VARCHAR,
    glyburide VARCHAR,
    tolbutamide VARCHAR,
    pioglitazone VARCHAR,
    rosiglitazone VARCHAR,
    acarbose VARCHAR,
    miglitol VARCHAR,
    troglitazone VARCHAR,
    tolazamide VARCHAR,
    examide VARCHAR,
    citoglipton VARCHAR,
    insulin VARCHAR,
    "glyburide-metformin" VARCHAR,
    "glipizide-metformin" VARCHAR,
    "glimepiride-pioglitazone" VARCHAR,
    "metformin-rosiglitazone" VARCHAR,
    "metformin-pioglitazone" VARCHAR,
    change VARCHAR,
    diabetesMed VARCHAR,
    readmitted VARCHAR
);